### ISSUE TITLE
unstable errors when evaluating

### ISSUE THREAD

**Issue by Zhiyu-Chen** [tagucci/pythonrouge#20]
have a loop for creating different summaries, sometimes the following error will show up:

Traceback (most recent call last):
  File "<stdin>", line 22, in <module>
  File "/home/anaconda2/lib/python2.7/site-packages/pythonrouge/pythonrouge.py", line 340, in calc_score
    shutil.rmtree(self.temp_dir)
  File "/home/anaconda2/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/home/anaconda2/lib/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: './tmpNpaixY'

**Comment by Zhiyu-Chen** [comment]
solved by changing  file "/home/anaconda2/lib/python2.7/site-packages/pythonrouge/pythonrouge.py", line 340, in calc_score

os.system("rm -rf " + self.temp_dir)

it seems to be a bug of shutil.rmtree: http://code.activestate.com/lists/python-list/159050/
