### ISSUE TITLE
Non-zero exit status 79

### ISSUE THREAD

**Issue by alanwang93** [tagucci/pythonrouge#26]
Hi,

I tried the example code on OSX 10.13.2, with both Python 3.6 and Python 2.7, and get the error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pythonrouge.py", line 334, in calc_score
    output = subprocess.check_output(rouge_cmd, stderr=subprocess.STDOUT)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['perl', '/Users/xxx/bin/pythonrouge/pythonrouge/RELEASE-1.5.5/ROUGE-1.5.5.pl', '-e', '/Users/xxx/bin/pythonrouge/pythonrouge/RELEASE-1.5.5/data', '-a', '-n', '2', '-2', '4', '-u', '-x', '-l', '50', '-m', '-s', '-f', 'A', '-r', '1000', '-p', '0.5', '/tmp/tmpKCWgSB/setting.xml']' returned non-zero exit status 79
```
I cannot find solution online, could you please help me? Thanks!

**Comment by tagucci** [comment]
Could you try this command?
```
# move to pythonrouge dir you've installed
cd /Users/xxx/bin/pythonrouge/pythonrouge/RELEASE-1.5.5/data/
rm WordNet-2.0.exc.db # only if exist
cd WordNet-2.0-Exceptions
rm WordNet-2.0.exc.db # only if exist
./buildExeptionDB.pl . exc WordNet-2.0.exc.db
cd ../
ln -s WordNet-2.0-Exceptions/WordNet-2.0.exc.db WordNet-2.0.exc.db
```

**Comment by alanwang93** [comment]
Hi @tagucci , Thanks for your reply.
I tried the command, however, `./buildExeptionDB.pl . exc WordNet-2.0.exc.db` created a really large file (around 40G) and I had to stop because there is no more space in my laptop. Is it normal?

**Comment by AlJohri** [comment]
@tagucci I got the same issue as @alanwang93 above- the file being generated is humongous. Mine was around 20gb before my laptop filled up. Trying again after clearing up some space. Is this normal?

**Comment by AlJohri** [comment]
It finally finished at 70GB.

```
$ pwd
/Users/johria/Development/paradox/pythonrouge/RELEASE-1.5.5/data/WordNet-2.0-Exceptions
$ du -h WordNet-2.0.exc.db                                                                                                                        70G	WordNet-2.0.exc.db
```

😱

**Comment by AlJohri** [comment]
I found this answer https://github.com/tagucci/pythonrouge/issues/11#issuecomment-331739100 which directed me to run:

```
./buildExeptionDB.pl . ../smart_common_words.txt WordNet-2.0.exc.db
```

instead of

```
./buildExeptionDB.pl . exe WordNet-2.0.exc.db
```

This created a 16 MB file instead.
