### ISSUE TITLE
CalledProcessError

### ISSUE THREAD

**Issue by tanpengshi** [tagucci/pythonrouge#40]
I tried to run the same codes as introduced in the repo:

```
`from pythonrouge.pythonrouge import Pythonrouge`

summary = [[" Tokyo is the one of the biggest city in the world."]]
reference = [[["The capital of Japan, Tokyo, is the center of Japanese economy."]]]

rouge = Pythonrouge(summary_file_exist=False,
                    summary=summary, reference=reference,
                    n_gram=2, ROUGE_SU4=True, ROUGE_L=False,
                    recall_only=True, stemming=True, stopwords=True,
                    word_level=True, length_limit=True, length=50,
                    use_cf=False, cf=95, scoring_formula='average',
                    resampling=True, samples=1000, favor=True, p=0.5)

score = rouge.calc_score()
```

But still encounter the following error. I tried previous suggested solution but it didn't help. 

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/tanpengshi/anaconda3/envs/summary/lib/python3.6/site-packages/pythonrouge/pythonrouge.py", line 334, in calc_score
>     output = subprocess.check_output(rouge_cmd, stderr=subprocess.STDOUT)
>   File "/home/tanpengshi/anaconda3/envs/summary/lib/python3.6/subprocess.py", line 336, in check_output
>     **kwargs).stdout
>   File "/home/tanpengshi/anaconda3/envs/summary/lib/python3.6/subprocess.py", line 418, in run
>     output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['perl', '/home/tanpengshi/anaconda3/envs/summary/lib/python3.6/site-packages/pythonrouge/RELEASE-1.5.5/ROUGE-1.5.5.pl', '-e', '/home/tanpengshi/anaconda3/envs/summary/lib/python3.6/site-packages/pythonrouge/RELEASE-1.5.5/data', '-a', '-n', '2', '-2', '4', '-u', '-x', '-l', '50', '-m', '-s', '-f', 'A', '-r', '1000', '-p', '0.5', '/tmp/tmpkp6ecmzr/setting.xml']' returned non-zero exit status 2.

I am using Windows Subsystem for Linux (WSL) - Ubuntu. Kindly help, thank you!!! :)

**Comment by tanpengshi** [comment]
Typing this code in the WSL terminal worked for me:

`sudo apt-get install libxml-parser-perl`
