### ISSUE TITLE
getting error for output = subprocess.check_output([ROUGE_path, "-e", data_path, "-a", "-m", "-2", "4","-n", "3", abs_xml_path], stderr=subprocess.STDOUT)     

### ISSUE THREAD

**Issue by rpiryani** [tagucci/pythonrouge#5]
Traceback (most recent call last):

  File "<ipython-input-40-61a11dce20f1>", line 1, in <module>
    score = pythonrouge.pythonrouge(peer_sentence, model_sentence,ROUGE,data_path)

  File "pythonrouge\pythonrouge.py", line 65, in pythonrouge
    output = subprocess.check_output([sys.executable, ROUGE_path, "-e", data_path, "-a", "-m", "-2", "4","-n", "3", abs_xml_path], stderr=subprocess.STDOUT)

  File "C:\Users\rajesh\Anaconda\lib\subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)

  File "C:\Users\rajesh\Anaconda\lib\subprocess.py", line 710, in __init__
    errread, errwrite)

  File "C:\Users\rajesh\Anaconda\lib\subprocess.py", line 958, in _execute_child
    startupinfo)

WindowsError: [Error 193] %1 is not a valid Win32 application

**Comment by hilaw** [comment]
I'm having the same problem

**Comment by jPPuetz** [comment]
Should be working with adding `'perl'` to line 126 so it looks like:
`rouge_cmd = ['perl', ROUGE_path, "-e", data_path, "-a"]`

**Comment by tagucci** [comment]
Sorry for the late response. Issue #8 may can solve your problem.
